language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install --upgrade pip
  - pip install -r requirement.txt
# command to run tests
script: 
  - scrapy runspider test_scrapy.py
